spring:
  profiles:
    active: prod  # 기본 활성화 프로필

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_id}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false
    cloudfront:
      domain: ${CLOUDFRONT_DOMAIN}

  jwt:
    secret: ${JWT_secret}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
  api-docs:
    path: /v3/api-docs
  show-actuator: true